/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":domain"))

    implementation ("org.mybatis:mybatis:3.5.11")
    implementation ("org.junit.jupiter:junit-jupiter-api:5.10.0")
    implementation ("org.junit.jupiter:junit-jupiter:5.10.0")

    testImplementation("mysql:mysql-connector-java:8.0.32")
    //testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
    testImplementation("com.h2database:h2:2.2.224")

}
