-- Inserts for the BRAND table
INSERT INTO BRAND (BRAND_NAME) VALUES ('Ferrari');
INSERT INTO BRAND (BRAND_NAME) VALUES ('Porsche');
INSERT INTO BRAND (BRAND_NAME) VALUES ('Lamborghini');
INSERT INTO BRAND (BRAND_NAME) VALUES ('Mercedes');
INSERT INTO BRAND (BRAND_NAME) VALUES ('Audi');


-- Inserts for the CAR table
INSERT INTO CAR (ID_BRAND, MODEL_NAME) VALUES (1, '488 GT3'); -- Ferrari 488 GT3
INSERT INTO CAR (ID_BRAND, MODEL_NAME) VALUES (2, '911 GT3 R'); -- Porsche 911 GT3 R
INSERT INTO CAR (ID_BRAND, MODEL_NAME) VALUES (3, 'Huracan GT3'); -- Lamborghini Huracan GT3
INSERT INTO CAR (ID_BRAND, MODEL_NAME) VALUES (4, 'AMG GT3'); -- Mercedes AMG GT3
INSERT INTO CAR (ID_BRAND, MODEL_NAME) VALUES (5, 'R8 LMS'); -- Audi R8 LMS


-- Inserts for the DRIVER table
INSERT INTO DRIVER (FIRST_NAME, LAST_NAME, NATIONALITY, BIRTHDATE) VALUES ('Lewis', 'Hamilton', 'British', '1985-01-07');
INSERT INTO DRIVER (FIRST_NAME, LAST_NAME, NATIONALITY, BIRTHDATE) VALUES ('Sebastian', 'Vettel', 'German', '1987-07-03');
INSERT INTO DRIVER (FIRST_NAME, LAST_NAME, NATIONALITY, BIRTHDATE) VALUES ('Max', 'Verstappen', 'Dutch', '1997-09-30');
INSERT INTO DRIVER (FIRST_NAME, LAST_NAME, NATIONALITY, BIRTHDATE) VALUES ('Charles', 'Leclerc', 'Monacan', '1997-10-16');
INSERT INTO DRIVER (FIRST_NAME, LAST_NAME, NATIONALITY, BIRTHDATE) VALUES ('Valtteri', 'Bottas', 'Finnish', '1989-08-28');


-- Inserts for the BRAND_DATA table
INSERT INTO BRAND_DATA (ID_BRAND, COUNTRY_OF_ORIGIN, CONTACT_INFO) VALUES (1, 'Italy', 'Maranello, Italy - info@ferrari.com');
INSERT INTO BRAND_DATA (ID_BRAND, COUNTRY_OF_ORIGIN, CONTACT_INFO) VALUES (2, 'Germany', 'Stuttgart, Germany - info@porsche.com');
INSERT INTO BRAND_DATA (ID_BRAND, COUNTRY_OF_ORIGIN, CONTACT_INFO) VALUES (3, 'Italy', 'Sant Agata Bolognese, Italy - info@lamborghini.com');
INSERT INTO BRAND_DATA (ID_BRAND, COUNTRY_OF_ORIGIN, CONTACT_INFO) VALUES (4, 'Germany', 'Affalterbach, Germany - info@mercedes-benz.com');
INSERT INTO BRAND_DATA (ID_BRAND, COUNTRY_OF_ORIGIN, CONTACT_INFO) VALUES (5, 'Germany', 'Ingolstadt, Germany - info@audi.com');


INSERT INTO CAR_DATA (ID_CAR, HORSEPOWER, WEIGHT) VALUES (1, 600, 1230);
INSERT INTO CAR_DATA (ID_CAR, HORSEPOWER, WEIGHT) VALUES (2, 500, 1250);
INSERT INTO CAR_DATA (ID_CAR, HORSEPOWER, WEIGHT) VALUES (3, 580, 1240);
INSERT INTO CAR_DATA (ID_CAR, HORSEPOWER, WEIGHT) VALUES (4, 550, 1260);
INSERT INTO CAR_DATA (ID_CAR, HORSEPOWER, WEIGHT) VALUES (5, 560, 1255);


-- Inserts for the CIRCUIT table
INSERT INTO CIRCUIT (CIRCUIT_NAME, COUNTRY, LENGTH_KM) VALUES ('Monza', 'Italy', 5.793);
INSERT INTO CIRCUIT (CIRCUIT_NAME, COUNTRY, LENGTH_KM) VALUES ('Silverstone', 'UK', 5.891);
INSERT INTO CIRCUIT (CIRCUIT_NAME, COUNTRY, LENGTH_KM) VALUES ('Nurburgring', 'Germany', 5.148);
INSERT INTO CIRCUIT (CIRCUIT_NAME, COUNTRY, LENGTH_KM) VALUES ('Spa-Francorchamps', 'Belgium', 7.004);
INSERT INTO CIRCUIT (CIRCUIT_NAME, COUNTRY, LENGTH_KM) VALUES ('Le Mans', 'France', 13.626);


-- Inserts for the RACE table
INSERT INTO RACE (ID_CIRCUIT, RACE_NAME, RACE_DATE) VALUES (1, 'Italian GP', '2024-05-01');
INSERT INTO RACE (ID_CIRCUIT, RACE_NAME, RACE_DATE) VALUES (2, 'British GP', '2024-06-01');
INSERT INTO RACE (ID_CIRCUIT, RACE_NAME, RACE_DATE) VALUES (3, 'German GP', '2024-07-01');


