/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":domain"))
    implementation(project(":domain-implementations:jdbc"))
    implementation(project(":domain-implementations:jpa"))
    implementation("com.github.freva:ascii-table:1.8.0")}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
